### ISSUE TITLE
提案方法についての検討

### ISSUE THREAD

**Issue by halsk** [meti-oi-startups/METI-JPO-Model-Contract#24]
@meti-oi-startups-team 様、今は、テキストファイルを作ってPull Request を送る形式になっていますが、Markdown ファイルが追加されたことにより、わざわざ .txt ファイルを作成しなくても **直接ファイルを修正して提案を送る** ということが可能になります。

その場合、以下の手順になります。

1. markdown を選択
![image](https://user-images.githubusercontent.com/16509/118996646-034be980-b9c3-11eb-93c0-ac221736a2c6.png)

2. 修正したい契約書を選択
![image](https://user-images.githubusercontent.com/16509/118996966-40b07700-b9c3-11eb-84f0-5395dc50d2ee.png)

3. 右上の鉛筆ボタンを押す
![image](https://user-images.githubusercontent.com/16509/118997138-62a9f980-b9c3-11eb-99d0-d49506b7679c.png)

4. エディタに変わるので、そのまま修正する
![image](https://user-images.githubusercontent.com/16509/118997240-7c4b4100-b9c3-11eb-8800-a2d2e2ce3d31.png)

5. 必要な修正をしたら、修正内容を入れて`Propose Changes` ボタンを押す
![image](https://user-images.githubusercontent.com/16509/118997382-971db580-b9c3-11eb-9c34-c36ac22c8063.png)

6. 内容を確認し、`Create Pull Request` を押す
![image](https://user-images.githubusercontent.com/16509/118998536-7c980c00-b9c4-11eb-8323-21791868c775.png)

7. 変更内容を再度確認し、`Create Pull Request` を押す
![image](https://user-images.githubusercontent.com/16509/118998067-1b703880-b9c4-11eb-8f1d-6416fb04fd9c.png)

以上で完了です。

![image](https://user-images.githubusercontent.com/16509/118998141-29be5480-b9c4-11eb-980c-9d1d201bdd1a.png)

**Comment by kvaluation** [comment]
Markdownに提案ができるのは素晴らしく、ありがとうございます。

今回はないかも知れませんが、法改正等のパブコメに対しては、ご承知のように、各種の団体が修正案とともに意見を述べ、団体のWebサイトに提出意見を掲載するような実務もあります。

例　http://www.jla.or.jp/demand/tabid/78/Default.aspx?itemid=5567

1つのまとまった意見を提出するニーズもあるかと思いますので、textなどのファイルでの意見提出もあわせて受け付けて頂けるとよろしいかと思われます。

**Comment by kvaluation** [comment]
@meti-oi-startups-team 様　issueで少し不特定の方と意見交換してから、実際の文言（Markdown表記）に対する修正案の提出という流れもあって良さそうですが、トライアル的に挑戦してみても良いでしょうか。

理想的には下記のようなイメージです。

issue #xx 第？条の「○○」との表現の意味するところ
Aさん　条項への違和感表明。修正案はぼんやりしている。
Bさん　ついでの違和感なり背景の理解を表明。修正対象がはっきりしてくる。
Cさん　修正案を提案
Aさん　修正案への希望
Bさん　すごいまとめの修正案を提案
Aさん　Bさんにプルリクの作業を依頼
close

**Comment by meti-oi-startups-team** [comment]
@kvaluation 様､ご提案ありがとうございます｡ ぜひ意見交換の場を作っていただければと思います｡

**Comment by meti-oi-startups-team** [comment]
@kvaluation 様
> 1つのまとまった意見を提出するニーズもあるかと思いますので、textなどのファイルでの意見提出もあわせて受け付けて頂けるとよろしいかと思われます

おっしゃる通り､今回想定しております意見提出していただけそうな弁護士の方々､スタートアップ･事業会社の法務の方々が出し易い環境も残したいと考えております｡

suggestionフォルダでのtxtでの応募の道も残そうと思います｡失礼いたしました｡

**Comment by halsk** [comment]
@meti-oi-startups-team @kvaluation 
#35  で提案してみましたのでご確認ください！

**Comment by halsk** [comment]
取り込んでいただきました。
@kvaluation 

ご確認ください！
