### ISSUE TITLE
条項・条文をcode blockで括る際に自動改行されないことへの対応策

### ISSUE THREAD

**Issue by kvaluation** [meti-oi-startups/METI-JPO-Model-Contract#33]
## 問題意識
法律や契約書の条文を扱う日本の実務では、条文部分を細線の四角で囲むことで、説明文と分離することが行われております。
GitHubのMarkdown表記で一番近いのはcode blockかと思われます。

しかし、code blockでは、1文が長いと改行されず、水平方向のスライダーを操作しなければ読めません。
インラインクオートや、引用は解決策の一案となりますが、法律関係者がぱっとみてそこが条文・条項であると認識するためには何らかの慣れが必要です（すみません）。

## 実例
1. code block (水平スライドしないと全文を読めない)
```
第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。
```
2. インラインクオート
``` 第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。 ```

3. 引用
> 第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。

上記の状況で、GitHubのMarkdownの直接的な記述で解決する方法は発見できませんでした（2021年5月21日）

## Chrome側で対応
code block内でwrapしたいという要望対応する拡張機能がありました。
https://chrome.google.com/webstore/detail/github-pre-utility/ohbmbjnjnkbfnmilcpklobimhkbdcdjl

<img width="330" alt="wrapAuto" src="https://user-images.githubusercontent.com/60703087/119082806-ca9b2700-ba39-11eb-9345-0b877448aaca.png">

有効にして、拡張機能設定の詳細→ wrap を auto とすることで、次の表記になります。
<img width="1034" alt="拡張機能" src="https://user-images.githubusercontent.com/60703087/119082843-ddadf700-ba39-11eb-9248-973147962cb5.png">

他にもっと良い案がありそうに思いますが、とりあえずの調査結果です。

**Comment by sky-y** [comment]
[table記法](https://github.github.com/gfm/#tables-extension-)を使う方法があります。
「条文部分を細線の四角で囲むこと」という条件にマッチします。

ただしGFMの仕様上、**必ず表見出しをつける**必要があります。
（これを積極的に活用するなら、「条文」とか「第○条」のようにキャプションをつける、という利用方法もあります）

## 例1

### コード

```
|【オプション2　-　秘密情報の範囲：要秘密指定（口頭開示の事後指定無し）】|
| --- |
|第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。|
```

### プレビュー

|【オプション2　-　秘密情報の範囲：要秘密指定（口頭開示の事後指定無し）】|
| --- |
|第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。|

## 例2（左寄せ）

### コード

```
|【オプション2　-　秘密情報の範囲：要秘密指定（口頭開示の事後指定無し）】|
| :--- |
|第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。|
```

### プレビュー

|【オプション2　-　秘密情報の範囲：要秘密指定（口頭開示の事後指定無し）】|
| :--- |
|第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。|

## 補足

いくつか実験してみました。

- `style`属性は無効化される
- `div` 要素で囲むと中のcodeblockが無効化される
- `textarea`要素は無効化される

https://github.com/sky-y/sample-linebreak-for-long-code

**Comment by halsk** [comment]
おおー。table 使うのはありですね！
例2（左寄せ）が良さそう・・・

**Comment by meti-oi-startups-team** [comment]
アイデアありがとうございます｡
1_モデル契約書ver1.0 秘密保持契約書（新素材）について例２でやってみます｡

**Comment by meti-oi-startups-team** [comment]
修正してみました｡
悩み
･Tableの中に改行があると行が増えてしまい記述の判読性が悪くなる｡
･Tableの中だと目次のリンクが切れるようです｡

**Comment by takker99** [comment]
> Tableの中だと目次のリンクが切れるようです｡

HTML tagを直接使うのはどうでしょうか？
表見出しを付ける必要がなくなり、代わりに普通の見出しを使うことができます

### コード

```markdown
#### 【オプション2　-　秘密情報の範囲：要秘密指定（口頭開示の事後指定無し）】

<table>
  <tbody>
    <tr>
      <td>第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。
      </td>
    </tr>
  </tbody>
</table>
```

### プレビュー

#### 【オプション2　-　秘密情報の範囲：要秘密指定（口頭開示の事後指定無し）】
<table>
  <tbody>
    <tr>
      <td>第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。
      </td>
    </tr>
  </tbody>
</table>

---
CSSで枠を付けられたら一番シンプルなのですが、`style`属性が無効になってしまうのでは無理そうですね……

**Comment by kvaluation** [comment]
新時代を切り拓く現場にいることができて、長生きして良かったなと思いました。ありがとうございます。

条文については、

1. プルリクなど修正しやすい。
2. computer program source codeと同様に、1行単位で修正を記録できたら素晴らしい。
3. 今回、解説付きの文章ですが、最終的に条文（条項）だけを抜き出して、契約書の形のデータで使いたいです（改行記号などが入っていない方が使いやすい）。
4. 第○条（h1）、第○項 (h2)、第○号 (h3)という三階層が通常ですが、省庁および法学書でこの階層に応じてfont sizeを階層化したりはしていないです。条・項・号でそれぞれ改行はします。
5. 全体的に、条文の文中で「前条」「第２条」などと引用するため、条文の番号で探しやすいと嬉しいです。

私としては、デジタルなので、今までの印刷物や省庁の実務に過度に合わせようとすることなく、GitHub使うならこのあたりの使い方をしてもらえたらお互いに生産性が高い、ということを目指せたらと感じております。

重なりますが、法律関係者や省庁で立法に関与しうる人が、生まれて始めて、条文の文章について、GitHubの１行単位の修正記録のページをみるときに、感動してもらうことを目指せたら面白く、そのGitHubらしい修正記録の綺麗さを維持できるようにしつつ、この条文表現の仕方を選んでいって頂けたらと思います。

WebページをGitHubで管理したりしたことがないのこともあり、皆様のお知恵に感謝しております。ありがとうございます。

**Comment by halsk** [comment]
みなさんありがとうございます！
見た目的には @takker99 さんの最後の案が一番課題を解決しています。ありがとうございます。
一方で、Markdown の構造的に美しくは無いのが難点ではありますね。

私も、 @kvaluation さんの

>私としては、デジタルなので、今までの印刷物や省庁の実務に過度に合わせようとすることなく、GitHub使うならこのあたりの使い方をしてもらえたらお互いに生産性が高い、ということを目指せたらと感じております。

という意見に同意で、文章構造的には

<pre>
```lawtext
条文
```
</pre>

みたいな書き方ができると美しくて、引用されている条文部分だけをまとめて抽出する、といった使い方も可能です。
過度に、GitHub Markdown Preview への最適化を目指さないほうが良い気がしてきました。

上記のようにしてしまうと改行されない、囲み枠が出ないという問題については、chrome extension などを作るという手もありますね。

皆さんのご意見もぜひお聞かせください。

**Comment by rinsuki** [comment]
Chrome Extension というのは権限があるサイトに対して「コードブロックを改行させたい」というにはいささか強すぎる権限を持っているため、それ専用の Chrome Extension の作成ではなく、Stylus https://github.com/openstyles/stylus などの**既にある程度利用されている**ユーザーが任意のサイトにCSSを注入できる Chrome Extension を利用することをおすすめしたいです。

また、GitHub Pages には Markdown を自動で HTML に変換する機能が付いていて、そちらであればコードブロックを折り返すなどのカスタムをしたCSSを埋め込む事も可能だと思うので、閲覧は GitHub Pages で、という方向性でもいいかもしれません。

**Comment by yoshitomo-g** [comment]
法的な文章を扱った経験のほとんどない門外漢なので、的外れなことを言っているかもしれませんがご容赦ください。
また、技術的に可能かどうかの前段階で、議論するにあたっての前提条件をどうするかというところの話になります。あいまいなままで進行しているようなのが気になりまして、参加させていただきました。

気になったのは、次の3点です。

### 見た目と意味のどちらを優先するのか
これは、かつてHTMLで議論された話で、項目タイトルの意味でフォントサイズ変更や太字にするのではなく、項目タイトルとしてマークアップ（意味づけ）して見た目はスタイルシートに任せるべきということです。

### 「条文」なのか「引用の中の条文」なのか
見た目を優先するのであれば無視してください。

意味を優先する場合で、「引用の中の条文」であるなら引用としてマークアップするべきだと思います。code block はコンピューターコードを意味するマークアップになりますし、テーブルは引用を意味しません。
むき出しの「条文」の場合に文章の構造としてどのような意味合いになるのかは、すみませんが知識がないので判断はお任せしたいと思います。

### 将来もGitHubを前提にしていくのかどうか
GitHub以外に変更する可能性があるのであれば、見た目よりも意味を優先して考えるべきかと思います。見た目を優先するとGitHubに依存してしまい、別のプラットフォームでは表示が大きく異なってしまう危険性があります。
テーブルであれば、枠の線が表示されないこともあるかもしれません。ブログサービスで乗り換えやデザインテーマの変更をしたことがある方は、同様の経験があるのではないでしょうか。

**Comment by halsk** [comment]
確かに Chrome Extension は、やめたほうが良さそうですね。
性格的に、GitHubを前提にしなくてはいけない、ということは無いと思います。
構造的に正しい文章を目指し、閲覧は GitHub Pages で、というのが一番良さそうに思います。
ちょっと自分のリポジトリで色々実験してみますね。

**Comment by halsk** [comment]
> 「条文」なのか「引用の中の条文」なのか

こちらについては、今回の場合は引用でもあるのかなとも思ったのですが、どうなんでしょうね。
@kvaluation さんはどう思われますか

**Comment by kvaluation** [comment]
みなさまありがとうございます。

GitHubを使うのであれば、条文をcodeとして扱い、法改正や契約更新による条文の文章の変更をGitで履歴管理してみたいです。

"```lawtext"

は、プログラム言語を指定するみたいな比喩で使えて、理想的ですばらしいです。

今回は、例えば、

<table>
  <tbody>
    <tr>
      <td>第1条　本契約において「秘密情報」とは、本目的のために、開示者が開示等する際に秘密である旨を明示した営業上または技術上の情報、および、これらを含む記録媒体、ならびに、素材、機器およびその他有体物をいうものとする。
      </td>
    </tr>
  </tbody>
</table>

という原案に対して、
「素材、機器およびその他有体物」→「 **本目的のために提供された原材料、** 素材、機器およびその他有体物」というプルリクエスト、その他プルリクエストがあった際に、

どの修正案が最終的に採用されたかの履歴を、Git管理したいです。このプルリクは、たとえば、「秘密管理のシールなしで提供された物を含む」など意図が１行ぐらいで一緒に管理されていくイメージです。

**Comment by kvaluation** [comment]
引用については、具体例をみてください。条文を逐条解説する際の印刷物でのスタイルです。

### 縦書き
特許庁『工業所有権法（産業財産権法）逐条解説〔第21版〕』
特許法１条と、その解説
<img width="283" alt="スクリーンショット 2021-05-22 21 41 39" src="https://user-images.githubusercontent.com/60703087/119227668-0b826100-bb4a-11eb-8b56-b4d1c4d89700.png">

### 横書き
経済産業省　知的財産政策室
不正競争防止法　逐条解説
https://www.meti.go.jp/policy/economy/chizai/chiteki/pdf/20190701Chikujyou.pdf
<img width="618" alt="スクリーンショット 2021-05-22 21 44 36" src="https://user-images.githubusercontent.com/60703087/119227763-7af85080-bb4a-11eb-95f2-61aa116d4d24.png">

こんな見た目ですと、条文・条項と、その解説である、というのが法律系の実務家や専門家にとってわりと分かりやすいです。

論理的には、条文だけのファイルが別途あって、その行数で引用（L12-L13など）しながら解説するファイルを別途つくるのかと思いますが、条文と解説が混在した１ファイルで修正案を考えて頂く方が、作成側も読み手も簡易な感じします。

## ご提案
まずは見た目優先でいかがでしょうか。"```lawtext"などが実現できるまで、暫定的に、作業も楽で、読み手も読みやすい妥協点で良いかと思われます。

今回は、意見募集も始まっていますので、現状のままでも良いと思います。見た目は私も HTML tag で括って頂くのが良かったです。

code blockで、実線の囲み枠でなく、背景色が他と違っても、違和感ありません。ただ、codeblockですと、自動改行なしが、水平スクロールで読まなければならず、読み手の集中をとぎらせそうです。

実際に pull request を作って見たりしながら、今回の件かまた別の件かに向けてより良くできたらと思います。

個人のリポジトリ（のブランチ）で、HTML tag で括ってみましたとか、他の形式にしてみましたなどの情報がありましたら、試しにいってみますので教えてください。

**Comment by hkk** [comment]
下記のように記述すると

<pre>
```lawtext
文章
```
</pre>

Github Markdown Preview では以下のHTMLにフォーマットされるので、

```
<pre lang="lawtext">
 <code>
   文章
 </code>
</pre>
```

該当する`<code>`タグのみで改行が有効になるよう、スタイルを変更(`style="white-space: pre-wrap;"`)するサンプルのChrome Extensionを作ってみました。
https://github.com/hkk/formatter-chrome-extension-sample

manifest.json
```
{
  "name": "formatter sample",
  "version": "0.1",
  "manifest_version": 3,
  "description": "formatter extension sample",
  "background": {
    "service_worker": "background.js"
  },
  "permissions": [
    "tabs",
    "scripting"
  ],
  "host_permissions": [
    "https://github.com/*"
  ]
}
```

background.js
```
chrome.tabs.onUpdated.addListener(function(tabId, info, tab) {
    if (info.status === 'complete' && tab.url.indexOf('https://github.com/') !== -1) {
        chrome.scripting.executeScript({
            target: {tabId: tabId},
            files: ['content-script.js']
        });
    }
});
```

content-script.js
```
_update_code();

if (observer) {
    observer.disconnect();
    observer = null;
}

var target = document.getElementsByClassName('commit-preview')[0];
if (target) {
    var observer = new MutationObserver((mutations) => {
        _update_code();
    });
    var config = {
        childList: true,
        characterData: true,
        subtree: true
    };
    observer.observe(target, config);
}

function _update_code() {
    var elements = document.querySelectorAll('pre[lang="lawtext"] code');
    elements.forEach((element) => {
        element.style.whiteSpace = 'pre-wrap';
    });
}
```

**Comment by yoshitomo-g** [comment]
なるほど。今回対象となる文書については全て逐条解説ありなので、条文の引用＋解説 という構造になるのですね。

また、@kvaluation さんが提示してくださった例（https://github.com/meti-oi-startups/METI-JPO-Model-Contract/issues/33#issuecomment-846409215 ）の形が業界的な定番ということなので、見た目がかなり重要ということもわかりました。

ひとまずは次のような感じになりますでしょうか。

- 見た目と意味のどちらを優先するのか → 定番の見た目になることを優先
- 「条文」なのか「引用の中の条文」なのか → 「引用の中の条文」（逐条解説なので）
- 将来もGitHubを前提にしていくのかどうか → 少なくとも今回の意見募集はGitHub

これを前提とするなら、@takker99 さんの案（https://github.com/meti-oi-startups/METI-JPO-Model-Contract/issues/33#issuecomment-846039712 ）が見た目には一番わかりやすく思えます。編集は少し慣れが必要かもしれませんが・・・。

次点でブロック引用でしょうか。表示が引用を意味していることを認識してしまえば、目視での判別も難しくないかと。機械的にも認識できるので、例えば音声リーダーの対応も期待できます。編集も難しくない。
私個人としては、これが一番良いと感じました。

改行位置を強制される素の code block は厳しいですね。今回の場合は強制される必要がありませんし、長い行を隙間から覗くように読むのは大変です。
個人的に特に読みにくいなぁと感じたものを選んでみましたが、どうでしょうか。
```
第2条　受領者は、善良なる管理者が払うべき注意義務をもって秘密情報を管理し、その秘密を保持するものとし、開示者の事前の書面による承諾なしに第三者に対して開示等または漏えいしてはならない。
2　前項の定めにかかわらず、受領者は、秘密情報を、本目的のために必要な範囲のみにおいて、受領者の役員および従業員（以下「役員等」という。）に限り開示等できるものとする。
3　受領者は、前項に定める開示等に際して、役員等に対し、秘密情報の漏洩、滅失、毀損の防止等の安全管理が図られるよう必要かつ適切な監督を行い、その在職中および退職後も本契約に定める秘密保持義務を負わせるものとする。役員等による秘密情報の開示等、漏洩、本目的以外の目的での使用については、当該役員等が所属する受領者による秘密情報の開示等、漏洩、本目的以外の目的での使用とみなす。
4　受領者は、次項に定める場合を除き、秘密情報を第三者に開示等する場合には、書面により開示者の事前承諾を得なければならない。この場合、受領者は、当該第三者に対して本契約書と同等の義務を負わせ、これを遵守させる義務を負うものとする。
5　前各項の定めにかかわらず、受領者は、次の各号に定める場合、当該秘密情報を開示等することができるものとする。（ただし、1号または2号に該当する場合には可能な限り事前に開示者に通知するものとする。）また、受領者は、かかる開示等を行った場合には、その旨を遅滞なく開示者に対して通知するものとする。
①　法令の定めに基づき開示等すべき場合
②　裁判所の命令、監督官公庁またはその他法令・規則の定めに従った要求がある場合
③　受領者が、弁護士、公認会計士、税理士、司法書士等、秘密保持義務を法律上負担する者に相談する必要がある場合
6　本条第1項ないし第3項の定めにかかわらず、甲および乙は、相手方の事前の承諾なく、以下の事実を第三者に公表することができるものとする。
甲乙間で、甲が開発した放熱特性を有する新規素材αを用いた共同研究の検討が開始された事実
```

---
将来的には、ワープロソフトの感覚で編集すると[法令標準XMLスキーマ](https://elaws.e-gov.go.jp/help/)準拠で保存できて、それを履歴管理できるような形になるといいなぁと思います。見やすい形に変換する技術はできていますから、差分と理由も見れるようになると、あとから経緯の確認が必要になったときに便利になりそうです。

**Comment by taisukef** [comment]
Markdownビューワーを別途作って対応するのはどうでしょう？

サンプル
https://code4fukui.github.io/Markdown/?url=https://code4fukui.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md

CSSを適応したサンプル
https://code4fukui.github.io/Markdown/?url=https://code4fukui.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md&css=https://code4fukui.github.io/Markdown/test/style.css

上記で適応したCSS
https://code4fukui.github.io/Markdown/test/style.css

各文書まとめリンク
https://github.com/code4fukui/METI-JPO-Model-Contract/blob/markdown/README.md

URLパラメーターでスタイルシートを適応することも可能です
https://github.com/code4fukui/Markdown/blob/master/README.md

**Comment by meti-oi-startups-team** [comment]
@taisukef 様、ご提案ありがとうございます｡下記URLが発行されました。
https://meti-oi-startups.github.io/METI-JPO-Model-Contract/
ここから @takker99 様の案で条文のところを四角囲いにしていく方針でよろしいでしょうか。

**Comment by taisukef** [comment]
設定とマージ、ありがとうございます。
今回のように表示をGitHubに依存しない形にすると、本件解決するので、本来のMarkdownのcode blockで括る形に戻すのが良いと思います。

[HTMLによって囲う方法](https://code4fukui.github.io/Markdown/?url=https://meti-oi-startups.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md#%E7%AC%AC2%E6%9D%A1%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81)
![image](https://user-images.githubusercontent.com/1715217/120243608-fffa0d00-c2a2-11eb-9638-c1b0debffe17.png)
- 記述にHTMLの知識が必要
- ページ内リンクも無効になってしまう

[Markdownで記述する方法](https://code4fukui.github.io/Markdown/?url=https://code4fukui.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md#%E7%AC%AC2%E6%9D%A1%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81)
![image](https://user-images.githubusercontent.com/1715217/120243695-4485a880-c2a3-11eb-936a-8d236985972b.png)
- テキストのみの平易な編集が可能

**Comment by taisukef** [comment]
1と7をcode blockを使うように修正しました
https://github.com/meti-oi-startups/METI-JPO-Model-Contract/pull/53

**Comment by munierujp** [comment]
@meti-oi-startups-team このリポジトリから https://meti-oi-startups.github.io/METI-JPO-Model-Contract/ への導線がないようなので、リポジトリの設定でウェブサイトにURLを設定されるといいかと思います。

![](https://user-images.githubusercontent.com/20086673/122081462-13c47800-ce3a-11eb-9945-2dd368c10305.gif)

**Comment by kvaluation** [comment]
多面的で、技術的で、未来に対する情熱をもった対話をありがとうございました。

実際に、pull requestしてみた感想です。 

1. 契約書や解説の文章を修正する際は、Edit<file>で作業をするため、ソフト改行が自動でなされる（Previewではソフト改行されない）。
2. Edit<file>での作業に際して、code blockの表記は集中の邪魔にならず、Edit状態でも他の部分との違いが見つけやすいのでありがたい。
3. 条項全体ではなく、 行を単位として最小限の修正をしてもらうようにうながせると良い。

本issueに関係するところは、1, 2などでしょうか。code blockで整理していただいて、作業しやすかったです。感謝申し上げます。

**Comment by kvaluation** [comment]
@hkk さん
> サンプルのChrome Extensionを作ってみました。
> https://github.com/hkk/formatter-chrome-extension-sample

ありがとうございます。今日までに自分、試せて無くて悲しいのですが、引き続きよろしくおねがいします。
弁護士さんたちは、GitHubは、microsoft wordの更新履歴管理とどう違うのか、という理解の仕方を模索していました。法務や知財の関係者が、なるべく違和感なくdiffを体験してもらえるようになると、だいぶ社会も変わってきそうな気がします。

@taisukef さん
ワークショップでの考え方や操作のご案内含め、色々とありがとうございます。本issueのCloseのタイミングなど私としては @taisukef さんにご一任したいのでMITI-JPOさんからの相談に引き続き絡んで差し上げてください。よろしくおねがいします。

**Comment by meti-oi-startups-team** [comment]
2回目の開始に伴いcloseとさせていただきます。
