### ISSUE TITLE
契約書に適したデザイン

### ISSUE THREAD

**Issue by taisukef** [meti-oi-startups/METI-JPO-Model-Contract#52]
契約書が読みやすいデザインを適応できるとより多くの人に見てもらえると思います。

Markdown.js で、文章とデザインを切り離すことができました。
https://github.com/meti-oi-startups/METI-JPO-Model-Contract/pull/49

CSSを自由に適応できます。
例えばこちら、縦書きで読む契約書です。（アラビア数字、漢数字変換などは別途必要そうですが）

![image](https://user-images.githubusercontent.com/1715217/120248891-e7deb980-c2b3-11eb-80ef-7eefc7a9a488.png)
https://code4fukui.github.io/Markdown/?url=https://code4fukui.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md&css=https://code4fukui.github.io/Markdown/test/vertical.css

こちらのリンクからCSSを自由に変更することができます
https://code4fukui.github.io/Markdown/?url=https://code4fukui.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md&css=https://code4fukui.github.io/Markdown/test/vertical.css&edit=on

**Comment by taisukef** [comment]
条文を左にfloatしてみたものです
https://code4fukui.github.io/Markdown/?url=https://code4fukui.github.io/METI-JPO-Model-Contract/1_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88%E6%96%B0%E7%B4%A0%E6%9D%90%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md&css=https://code4fukui.github.io/METI-JPO-Model-Contract/styles/separate.css
![image](https://user-images.githubusercontent.com/1715217/120395764-83356480-c370-11eb-8fce-b7515d63038a.png)

**Comment by meti-oi-startups-team** [comment]
2回目の開始に伴いcloseとさせていただきます。
