### ISSUE TITLE
中身に関する議論が活発に行われるようにするにはどうすればよいか

### ISSUE THREAD

**Issue by TakatsuguImaizumi** [meti-oi-startups/METI-JPO-Model-Contract#57]
## 問題意識

- 現状、markdownへの移行はほぼ完了していると理解している
  - 一部コードブロックに読みにくいところはあるものの
  - GitHub上で気軽に条文や解説に変更を加えることはできる状態には既にしていただいたといってよいと思われる
- 他方、肝心の内容面についての修正提案は今のところまったくない
  - 元々の解説の質が高いのはさておいても、スタートアップのモデル契約書に対する意見がまったくないはずがない
  - 興味を持っていただいている法曹関係者や企業法務部員はSNS等を見る限りそこそこいる印象
- 仮説
  - issueの記票やPull Requestを試みようとして躓いている法律関係者が多いのではないか
    - 単純に使い方が難しくて諦めるタイプ（ITスキルの問題）
    - OSS（ソフトウエアではないですが）開発に限らないGitHub上のお作法がわからなくて敷居を感じるタイプ（IT文化の問題）
  - このあたり、躓きの石があるなら取り除きたい

## Next Action

ご意見募集

**Comment by kvaluation** [comment]
ありがとうございます。Twitterで5/24に刺激を入れたりしてみたのですが、他の話題と比較して、または元々私に人望がなく、反応がありませんでした。内容面でも難しさがあるような気もします。
https://twitter.com/info_kvaluation/status/1396666212591935489

また、意見を出せる人の経験、立場、資格などもうすこし広いと良いのかも知れません。例えば、AIや新素材を直接は扱わないけれどもプログラミングや情報処理に詳しく、かつ、OSSや半導体関係を含めた契約条項の読み方にも慣れていらっしゃるエンジニアや大学教授・研究室ご関係者など、GitHubにも慣れていらっしゃり、ぜひ意見欲しいと思われます。

内容面での論点の案です。文体がTwitter向けですみません。

@meti-oi-startups-team 経済産業省・特許庁など、ご提案者や普及ご関係者は、どのあたりの論点で情報交換がなされていることをご期待なのか、個人的なお考えでも何かヒントあると嬉しいです。

## 論点1　デフォルトルール
　契約というのは、ある意味、民法によるデフォルトルールを当事者の合意で上書きするために行う。なので、その契約条項がないと将来どうなるのか（デフォルトルールだとどうなるのか）、民法や特別法の原則が解説にあると良いのだが、なかったりする。
　こちらのモデル案には、損害賠償条項とかあってもなくても変化しなさそうにも思われる条項も。

## 論点2　施行済み改正債権法との関係
　例えば瑕疵担保責任ではなく契約不適合責任へと考え方のシフトが明確になっている。
　契約するということは、デフォルトルールや業界の一般品質水準ではない内容で、不適合責任を負うということ。その注意喚起がどこかにあるか？

## 論点3　モデル契約書の使い方
　ベンチャーは弁護士に相談できる体制を整えておくべきで、モデル契約書をコピーすれば良いと考えるべきではない。誰もがしたことがないような類型の契約（例えば、Appleが音楽業界と交わしたデジタル配信など）こそが長期的利益を生む。

## 論点4　英語版・米国法準拠版
　モデル契約書に英語版、米国法準拠版がない。できれば中国対応も。日本法で契約しても日本市場という小さい世界しか対象にならない。残念ながら、日本は今そういうポジションではないだろうか。

## 論点5　知的財産に関する定義
　著作物や著作権を想定してなさそうな「知的財産、知的財産権」の使用例と、逆に、発明、ノウハウ、特許を意識してなさそうな「知的財産、知的財産権」の使用例がある。

## 論点6　弁理士
　弁理士資格保有者としては、色々な資格が列挙されている条項で弁理士が入っていないと、またかよ、感。弁理士のどなたか頑張って意見だしていただけないでしょうか？

## 論点7　無形資産の価値を高めるか
　ベンチャー側、市場をもつ事業会社側の双方にとって、その契約によって両社それぞれの無形資産（インタンジブルズ）をどう増加させようとしているのか、という発想を発見できない。広報との関係は少しあって好印象なので、IRや統合報告に書きたくなる内容となるまで、繋げて欲しい。

## 論点8　オープンソースとの関係
　オープンソースに貢献できている企業かどうかは、エンジニアの採用に直結する。
オープンソース活動への理念と矛盾・抵触する条項がないかは、企業や大学研究室それぞれであり、どう両立させるべきかモデル契約を使う人が気をつけることができるような、案内があると良い。

## その他
　その他、より良い未来のために、考えるべきことは多いだろうと思われます。会計側からも、リスク情報の開示が求められてきているところ、予見可能性を高める契約をまとめていく能力がより一層必要とされてきます。

**Comment by meti-oi-startups-team** [comment]
@TakatsuguImaizumi 様､ @kvaluation 様､当方と同じ問題意識を持ってくださり､大変心強く思っております｡ありがとうございます｡

まずはモデル契約書が､実際にどのように使われているのかを知りたいというのがスタートかと考えておりました｡kvaluation様に募集いただいたように(ありがとうございます)､スタートアップと事業会社との契約でモデル契約書を使って､こういう落としどころで､この条文をこう修正した｡というような生の声をいただきたいと思っております｡

お互いのパワーバランスの中で様々な交渉を経て契約が締結される過程でここが使い辛い､こういう考え方もあるということが反映していけたらと思ってます｡当初は例えばエンジニア出身のスタートアップの社長の方などに出していただけるのではないかと想定していたところです｡

役所としてはチャレンジングな取り組みではあるものの､未だモデル契約書に対するご意見がいただけていない現状に対しまして､オープンの場で意見を出しにくかったり､リーガル関係の方々のGitHubへプルリクすることだったりのハードルが取り除けないかと考えております｡

そこで急きょではございますが､弁護士の方々のコミュニティである一般社団法人Public Meets Innovation(PMI)さんのご協力で､会員様を対象としたワークショップを開催する運びとなりました｡もしよろしければZoomでどなたでもオブザーバー参加いただけるとのことですので､当方のメールアドレスmodel_contract@meti.go.jpにご連絡を頂けましたらZoomURLを送付させていただきます｡

日程は6/15(火)19:00~20:30でございます｡このコメント欄をご覧の方でご興味ある方はご連絡をいただけますと幸いです｡Issueでも案内します｡※もちろん弁理士の方も歓迎いたします :exclamation:

**Comment by kvaluation** [comment]
モデル契約書に反映して欲しい訳ではないが、自分なりの想定を加えた際の修正例というのを、途中まで作成してみました。

重要：モデル契約書本体へのプル・リクエストをしたい内容ではなく、特定用途に向けた詳細案という位置づけです。

[モデル契約書 ver1.0 秘密保持契約書（AI）　このブランチについて](https://github.com/kvaluation/METI-JPO-Model-Contract/blob/intangible-driven/5_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88AI%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md#%E3%81%93%E3%81%AE%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

経営デザインシートやデザイン経営を活用でき、オープン・イノベーションへのマインドを持っている経営者が、ビジネスの成功を目指すために、未来に向けてより良い準備をしてもらう趣旨のものです。

・X社、Y社のパーパス・企業理念の例
https://github.com/kvaluation/METI-JPO-Model-Contract/commit/4fce617a5a6e9bd6029ddd11ac2eda4b4843f61c#diff-2350635ef5dceea4180b7a213bbf8ed6ca47a3f40eb21376a178974d2ca50a65

・条項の修正案（途中）
https://github.com/kvaluation/METI-JPO-Model-Contract/commit/ee0e7c97a8ee241e3cb25e6caacd6c4e18d42a8f#diff-2350635ef5dceea4180b7a213bbf8ed6ca47a3f40eb21376a178974d2ca50a65

モデル契約書本体の進化と並行して、このようなブランチも作っていけるのは、デジタルやオープンの良さと思います。

将来的に、経済産業省殿・特許庁殿には、モデル契約書をこのままGitHubで管理いただけますと、研究会や団体、大学などがforkしながらモデル契約書案ベースの独自案をそれぞれのリポジトリで公表できます。

もちろん、各バリエーション（ブランチ）については、本家のリポジトリやそのwikiなどでご紹介いただき、モデル本体に取り組むべき提案があれば取り込んでいただくことも考えられます。

今回も、プルリクするほどではないが、特定用途向けの案文を書いてみた、という方は、どのように、こちらに報告すると良いか、ニーズの有無も探りつつ、ご案内できたらと思います（issue立ててもらえば良いかなあ）。

その他、議論しやすそうなテーマでissue（#60, #61, #62）とプルリクエスト (https://github.com/meti-oi-startups/METI-JPO-Model-Contract/pull/63#issue-669973361) をしてみました。内容にこだわりはありません。モデル契約書でGitHub活用というのは、こんな感じなのかな、という例です。

**Comment by uedatakayuki** [comment]
若干議論が飛んでしまいますが・・・
いきなりプルリクをしてくださいっていうのは、ハードルが高いし、議論もまとまらないなと感じました。

https://github.com/meti-oi-startups/METI-JPO-Model-Contract
>![Screen Shot 2021-06-16 at 22 09 29](https://user-images.githubusercontent.com/34021140/122224956-93f8e500-ceef-11eb-8025-c04e8acab56f.png)

例えば、

- issue作成のテンプレをちゃんと用意する
- 気になる点はテンプレに沿ってissue化してもらう
- ある程度方向性が固まった段階でプルリクをする

っていう方針にするだけでも全然違うかなと思います。

また、プルリクについても、マージの方針を決めておかないと無数にブランチが発生してそれはそれでごちゃごちゃになりそうだなという懸念を持ちました（今の参加人数であれば杞憂だとは思いますが・・ｗ）
あと、昨日どなたかが発言されていましたが、契約書毎だったり新素材編とAI編でレポジトリを分けるのはありだなと思いました。

**Comment by kvaluation** [comment]
@uedatakayuki ありがとうございます。

> あと、昨日どなたかが発言されていましたが、契約書毎だったり新素材編とAI編でレポジトリを分けるのはありだなと思いました。

そうですね。今後の法律分野でのGitHub活用に向けた知恵としては、普通の感覚より、議論の対象（１ページの文字数、１リポジトリに含まれるページ数）を細かくわけてもらえた方が対話しやすいと感じました。

今回のようなケースや、例えば中間試案へのパブコメなどでのGitHubご利用であれば、プルリクのマージは原則一切せず、政府事務局案の更新を反映させていただくのが良いかなとも思います。

事務局案を新たに書き起こすことなくプルリクそのままでよければマージいただいても良いですし。

新たな事務局案で更新いただく際に、残したいissueやプルリクを選んでいただいたり、パブコメで「ご意見への回答」とするところを、issueに一言いれておいていただいてからcloseするなどでも、経緯は格段に追いやすい状態で残せると思います。

**Comment by kvaluation** [comment]
> * issue作成のテンプレをちゃんと用意する

テンプレだけでなく、事務局側から、特に意見を集めたい部分の考え方の１枚紙をだしておいていただいて、それに意見を出していく方が、条項や解説に意見を重ねていくよりも対話しやすそうです。

今回ですと、「知的財産権の帰属に関する本モデル契約書での考え方」でA4にて1枚ぐらいの分量のものを本体とは別にだしておいていただくなど。

また、issueで優れたテンプレがあると皆さん楽になると思われますが、ご承知のようにパブコメであれば様式はないので、自由な意見提出も可能なルートを残しておくことも重要かと思います。

実際に皆様が手を動かしてくださったことで、次に繋がる知見が蓄積されてきたと思います。ありがとうございます。

**Comment by uedatakayuki** [comment]
>また、issueで優れたテンプレがあると皆さん楽になると思われますが、ご承知のようにパブコメであれば様式はないので、自由な意見提出も可能なルートを残しておくことも重要かと思います。

ありがとうございます。たしかに自由にコメントを出せるルートもほしいですね。
パブコメと違ってうまく皆さんで議論ができる場になればいいですね。

**Comment by meti-oi-startups-team** [comment]
2回目の開始に伴いClose致します。
