### ISSUE TITLE
専門家の例示から弁理士が抜けている

### ISSUE THREAD

**Issue by kvaluation** [meti-oi-startups/METI-JPO-Model-Contract#61]
例えば、モデル契約書 ver1.0 秘密保持契約書（AI）第２条第５項第３号に弁理士が入っておりません。

**Comment by uedatakayuki** [comment]
@meti-oi-startups-team こちらAI編のレポジトリへのtransferをお願いできますでしょうか。

**Comment by meti-oi-startups-team** [comment]
2回目の開始に伴いCloseとさせていただきます。
