### ISSUE TITLE
手続を履践

### ISSUE THREAD

**Issue by kvaluation** [meti-oi-startups/METI-JPO-Model-Contract#62]
[モデル契約書 ver1.0 秘密保持契約書（AI）](https://code4fukui.github.io/Markdown/?url=https://meti-oi-startups.github.io/METI-JPO-Model-Contract/5_%E3%83%A2%E3%83%87%E3%83%AB%E5%A5%91%E7%B4%84%E6%9B%B8v1_0_%E7%A7%98%E5%AF%86%E4%BF%9D%E6%8C%81%E5%A5%91%E7%B4%84%E6%9B%B8%EF%BC%88AI%E7%B7%A8%EF%BC%89_%E9%80%90%E6%9D%A1%E8%A7%A3%E8%AA%AC%E3%81%82%E3%82%8A.md)

「履践」は、大日本帝国憲法に使用例があるようですが、現代に馴染みがあると思われず、現行法でも使用例を発見できないので、他の用語とすることで、契約書を少しでも読みやすくすると良いのではないでしょうか。

`第5条　乙（介護事業者）が、個人情報の保護に関する法律に定める個人情報または匿名加工情報を含んだ対象データを甲（AI開発企業）に提供する場合には、法に定められている**手続を履践**していることを保証するものとする。`

代替案としては、例えば行政手続法第42条の規定振りなどから「手続を実施」「手続きを執らなければならない」などの表現が考えられます。

**Comment by uedatakayuki** [comment]
@meti-oi-startups-team こちらAI編のレポジトリへのtransferをお願いできますでしょうか。

**Comment by meti-oi-startups-team** [comment]
2回目の開始に伴いCloseとさせていただきます。
